template = "https://github.com/giellalt/template-lang-und"
rev_id = 133
template_sha = "3a3062923599df5f3471a3d9241f30f050f799b7"

[replacements]
__REPO__ = "lang-vot"
__UND2C__ = "vot"
__UNDEFINED__ = "Votic"
__UND__ = "vot"
