template = "https://github.com/giellalt/template-lang-und"
rev_id = 173
template_sha = "7f7aaa49ffc6ff6884deab8fb0fe6cae98efc3b8"

[replacements]
__REPO__ = "lang-vot"
__UND2C__ = "vot"
__UNDEFINED__ = "Votic"
__UND__ = "vot"
