template = "https://github.com/giellalt/template-lang-und"
rev_id = 169
template_sha = "e276366f8280e53d907be9b90035b3e59502b1d8"

[replacements]
__REPO__ = "lang-vot"
__UND2C__ = "vot"
__UNDEFINED__ = "Votic"
__UND__ = "vot"
